name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --config.strict-dep-builds=false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate and Build APK
        run: |
          EXPO_DIR=$(dirname $(find . -name "app.json" -not -path "*/node_modules/*" | head -n 1))
          cd $EXPO_DIR
          npx expo prebuild --platform android --no-install
          cd android
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$(pwd)/app/debug.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=androiddebugkey -Pandroid.injected.signing.key.password=android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: salah-tracker-apk
          path: "**/android/app/build/outputs/apk/release/app-release.apk"